format_version: 10
pipelines:
  backend:
    group: App-Deployments
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-795c8d6:
        git: https://github.com/naveendevops453/expense-anisble.git
        shallow_clone: true
        auto_update: true
        branch: main
    secure_variables:
      SSH_PASSWORD: "AES:g+WiSTADHzb1VO5WZzjYTg==:w1HwOTwfYWZ3RYwbTZEBjA=="
    environment_variables:
      component: backend
    template: ansible-app-deployment