format_version: 10
pipelines:
  backend:
    group: App-Deployments
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-795c8d6:
        git: https://github.com/naveendevops453/expense-anisble.git
        shallow_clone: true
        auto_update: true
        branch: main
    stages:
      - DEV:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            test-j:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - -l
                    command: ls


      - QA:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            test-j:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - -l
                    command: ls
                    run_if: passed

      - STAGE:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            test-j:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - -l
                    command: ls
                    run_if: passed

      - PROD:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            test-j:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - -l
                    command: ls
                    run_if: passed
