format_version: 10
pipelines:
  expense-mysql:
    group: ansibleGroup
    label_template: ${COUNT}
    materials:
      git-da613e5:
        git: https://github.com/naveendevops453/expense-anisble.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      ssh_password: "AES:6Orrfh48+lWMeRnsRVPYrw==:vZndmG9aRtSHa8pmFOEZEA=="
    stages:
      - DEV:
          fetch_materials: true
          environment_variables:
            env: dev
          approval:
            type: manual
          jobs:
            ansible-playbook:
              tasks:
                - exec:
                    arguments:
                      - run.sh
                      - mysql
                    command: bash #bash ansible.sh frontend
                    run_if: passed