format_version: 10
pipelines:
  ansible-app-deployment:
    group: App-Deployments
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-795c8d6:
        git: https://github.com/naveendevops453/expense-anisble.git
        shallow_clone: true
        auto_update: true
        branch: main
    secure_variables:
      SSH_PASSWORD: "AES:6Orrfh48+lWMeRnsRVPYrw==:vZndmG9aRtSHa8pmFOEZEA=="
    stages:
      - DEV:
          fetch_materials: true
          environment_variables:
            env: dev
          approval:
            type: manual
          jobs:
            ansible:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - run.sh
                    command: bash
      - QA:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            ansible:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - -l
                    command: ls
                    run_if: passed

      - STAGE:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            ansible:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - -l
                    command: ls
                    run_if: passed

      - PROD:
          fetch_materials: true
          environment_variables:
            env: dev
          approval:
            type: manual
          jobs:
            ansible:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - run.sh
                    command: bash
                    run_if: passed
